import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sticky wall",
  description: "Generated by create next app",
  icons: {
    icon: "icon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="flex px-6 w-screen">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
