import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./Components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="/favicon.ico"></link>
      </head>
      <body className={inter.className}>
        <main className="flex min-h-screen items-center space-x-5 ">
          <div className="flex flex-col ">
            <Sidebar />
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
